# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '111.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(-30, 90, 261, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_furniture = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_furniture.sizePolicy().hasHeightForWidth())
        self.img_furniture.setSizePolicy(sizePolicy)
        self.img_furniture.setMinimumSize(QtCore.QSize(75, 0))
        self.img_furniture.setStyleSheet("background: rgb(0, 0, 0)")
        self.img_furniture.setText("")
        self.img_furniture.setObjectName("img_furniture")
        self.horizontalLayout_2.addWidget(self.img_furniture)
        self.name_furniture = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_furniture.sizePolicy().hasHeightForWidth())
        self.name_furniture.setSizePolicy(sizePolicy)
        self.name_furniture.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_furniture.setFont(font)
        self.name_furniture.setObjectName("name_furniture")
        self.horizontalLayout_2.addWidget(self.name_furniture)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.add_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.add_button.setStyleSheet("QPushButton {\n"
"  background: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background: rgb(38, 132, 255)\n"
"}")
        self.add_button.setObjectName("add_button")
        self.verticalLayout_5.addWidget(self.add_button)
        self.change_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.change_button.setStyleSheet("QPushButton {\n"
"  background: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background: rgb(38, 132, 255)\n"
"}")
        self.change_button.setObjectName("change_button")
        self.verticalLayout_5.addWidget(self.change_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_furniture.setText(_translate("Form", "Название"))
        self.add_button.setText(_translate("Form", "add"))
        self.change_button.setText(_translate("Form", "change"))
