# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMainWindow, QLabel, QWidget, QVBoxLayout


class MainWindowClass(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 854)
        MainWindow.setMaximumSize(QtCore.QSize(1009, 854))
        MainWindow.setStyleSheet("background: rgb(118, 118, 118)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.save_load_horisontal_box = QtWidgets.QHBoxLayout()
        self.save_load_horisontal_box.setObjectName("save_load_horisontal_box")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setStyleSheet("QPushButton {\n"
                                       "  background: rgb(255, 0, 0);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "  background: rgb(38, 132, 255)\n"
                                       "}")
        self.save_button.setObjectName("save_button")
        self.save_load_horisontal_box.addWidget(self.save_button)
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setStyleSheet("QPushButton {\n"
                                       "  background: rgb(255, 0, 0);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "  background: rgb(38, 132, 255)\n"
                                       "}")
        self.load_button.setObjectName("load_button")
        self.save_load_horisontal_box.addWidget(self.load_button)
        self.verticalLayout.addLayout(self.save_load_horisontal_box)
        self.change_make = QtWidgets.QPushButton(self.centralwidget)
        self.change_make.setStyleSheet("QPushButton {\n"
                                       "  background: rgb(255, 0, 0);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "  background: rgb(38, 132, 255)\n"
                                       "}")
        self.change_make.setObjectName("change_make")
        self.verticalLayout.addWidget(self.change_make)
        self.auto_razvodchic = QtWidgets.QPushButton(self.centralwidget)
        self.auto_razvodchic.setStyleSheet("QPushButton {\n"
                                           "  background: rgb(255, 0, 0);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed{\n"
                                           "  background: rgb(38, 132, 255)\n"
                                           "}")
        self.auto_razvodchic.setObjectName("auto_razvodchic")
        self.verticalLayout.addWidget(self.auto_razvodchic)
        self.main_plan = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_plan.sizePolicy().hasHeightForWidth())
        self.main_plan.setSizePolicy(sizePolicy)
        self.main_plan.setMinimumSize(QtCore.QSize(700, 750))
        self.main_plan.setStyleSheet("background: rgb(0, 0, 0)")
        self.main_plan.setText("")
        self.main_plan.setObjectName("main_plan")
        self.verticalLayout.addWidget(self.main_plan)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.scroll_of_furniture = QtWidgets.QScrollArea(self.centralwidget)
        self.init_sctol()

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_of_furniture.sizePolicy().hasHeightForWidth())
        self.scroll_of_furniture.setSizePolicy(sizePolicy)
        self.scroll_of_furniture.setMinimumSize(QtCore.QSize(280, 0))
        self.scroll_of_furniture.setWidgetResizable(True)
        self.scroll_of_furniture.setObjectName("scroll_of_furniture")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 278, 760))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 261, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_furniture = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_furniture.sizePolicy().hasHeightForWidth())
        self.img_furniture.setSizePolicy(sizePolicy)
        self.img_furniture.setMinimumSize(QtCore.QSize(75, 0))
        self.img_furniture.setStyleSheet("background: rgb(0, 0, 0)")
        self.img_furniture.setText("")
        self.img_furniture.setObjectName("img_furniture")
        self.horizontalLayout_2.addWidget(self.img_furniture)
        self.name_furniture = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_furniture.sizePolicy().hasHeightForWidth())
        self.name_furniture.setSizePolicy(sizePolicy)
        self.name_furniture.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_furniture.setFont(font)
        self.name_furniture.setObjectName("name_furniture")
        self.horizontalLayout_2.addWidget(self.name_furniture)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.add_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.add_button.setStyleSheet("QPushButton {\n"
                                      "  background: rgb(255, 0, 0);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "  background: rgb(38, 132, 255)\n"
                                      "}")
        self.add_button.setObjectName("add_button")
        self.verticalLayout_5.addWidget(self.add_button)
        self.change_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.change_button.setStyleSheet("QPushButton {\n"
                                         "  background: rgb(255, 0, 0);\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed{\n"
                                         "  background: rgb(38, 132, 255)\n"
                                         "}")
        self.change_button.setObjectName("change_button")
        self.verticalLayout_5.addWidget(self.change_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)

        self.scroll_of_furniture.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_4.addWidget(self.scroll_of_furniture)
        self.add_furniture = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_furniture.sizePolicy().hasHeightForWidth())
        self.add_furniture.setSizePolicy(sizePolicy)
        self.add_furniture.setMinimumSize(QtCore.QSize(280, 0))
        self.add_furniture.setStyleSheet("QPushButton {\n"
                                         "  background: rgb(255, 0, 0);\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed{\n"
                                         "  background: rgb(255, 255, 0);\n"
                                         "}")
        self.add_furniture.setObjectName("add_furniture")
        self.verticalLayout_4.addWidget(self.add_furniture)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.save_button.setText(_translate("MainWindow", "Сохранить  дизайн"))
        self.load_button.setText(_translate("MainWindow", "Загрузить дизайн"))
        self.change_make.setText(_translate("MainWindow", "Изменить макет квартиры"))
        self.auto_razvodchic.setText(_translate("MainWindow", "Автоматически расставить "))
        self.name_furniture.setText(_translate("MainWindow", "Название"))
        self.add_button.setText(_translate("MainWindow", "add"))
        self.change_button.setText(_translate("MainWindow", "change"))
        self.add_furniture.setText(_translate("MainWindow", "Добавить свою мебель"))

    def init_sctol(self):
        self.widget = QWidget()
        self.vbox = QVBoxLayout()
        for i in range(1, 50):
            self.vbox.addWidget(self.verticalLayout_4)

        self.widget.setLayout(self.vbox)

        # Scroll Area Properties
        self.scroll_of_furniture.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scroll_of_furniture.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_of_furniture.setWidgetResizable(True)
        self.scroll_of_furniture.setWidget(self.widget)
