# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_plat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PIL import Image, ImageDraw
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QLabel, QWidget, QVBoxLayout, QApplication, QColorDialog
from PyQt5.QtCore import Qt, QPoint, QObject
from PyQt5.QtGui import QPen, QPainter, QImage, QPixmap
from PIL.ImageQt import ImageQt
import sqlite3


class NewPlatClass(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        Form = self

        self.drawing = False
        self.draw_flag = False
        self.brushSize = 2
        self.brushColor = (255, 255, 255)
        self.lastPoint = QPoint()

        Form.setObjectName("Form")
        Form.resize(749, 626)
        Form.setStyleSheet("background: rgb(118, 118, 118)")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plat_map = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plat_map.sizePolicy().hasHeightForWidth())
        self.plat_map.setSizePolicy(sizePolicy)
        self.plat_map.setMinimumSize(QtCore.QSize(600, 0))
        self.plat_map.setStyleSheet("background: rgb(0, 0, 0)")
        self.plat_map.setText("")
        self.plat_map.setObjectName("plat_map")
        self.horizontalLayout_2.addWidget(self.plat_map)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rendo_button = QtWidgets.QPushButton(Form)
        self.rendo_button.setStyleSheet("QPushButton {\n"
                                        "  background: rgb(255, 0, 0);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "  background: rgb(38, 132, 255)\n"
                                        "}")
        self.rendo_button.setObjectName("rendo_button")
        self.verticalLayout.addWidget(self.rendo_button)
        self.undo_button = QtWidgets.QPushButton(Form)
        self.undo_button.setStyleSheet("QPushButton {\n"
                                       "  background: rgb(255, 0, 0);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "  background: rgb(38, 132, 255)\n"
                                       "}")
        self.undo_button.setObjectName("undo_button")
        self.verticalLayout.addWidget(self.undo_button)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply_button = QtWidgets.QPushButton(Form)
        self.apply_button.setStyleSheet("QPushButton {\n"
                                        "  background: rgb(255, 0, 0);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "  background: rgb(255, 255, 0);\n"
                                        "}")
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout.addWidget(self.apply_button)
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setStyleSheet("QPushButton {\n"
                                       "  background: rgb(255, 0, 0);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "  background: rgb(255, 255, 0);\n"
                                       "}")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.rendo_button.setText(_translate("Form", "Вперёд"))
        self.undo_button.setText(_translate("Form", "Назад"))
        self.apply_button.setText(_translate("Form", "Применить"))
        self.exit_button.setText(_translate("Form", "Выйти"))

        self.im = Image.new('RGB', (self.plat_map.size().width(), self.plat_map.size().height()), 'black')
        self.old_im = Image.new('RGB', (self.plat_map.size().width(), self.plat_map.size().height()),
                                'black')
        self.undo_button.clicked.connect(self.undo)
        self.rendo_button.clicked.connect(self.rendo)
        self.apply_button.clicked.connect(self.apply)
        self.exit_button.clicked.connect(self.close)

    def undo(self):
        self.im, self.old_im = Image.new('RGB',
                                         (self.plat_map.size().width(), self.plat_map.size().height()),
                                         'black'), self.old_im.copy()
        self.pix = QPixmap.fromImage(ImageQt(self.im.convert("RGBA")))
        self.plat_map.setPixmap(self.pix)

    def rendo(self):
        self.im = self.old_im.copy()
        self.pix = QPixmap.fromImage(ImageQt(self.im.convert("RGBA")))
        self.plat_map.setPixmap(self.pix)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.drawing = True
            self.lastPoint = event.pos()

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Escape:
            self.draw_flag = False

    def mouseReleaseEvent(self, event):
        if event.button() == Qt.LeftButton:
            if self.draw_flag:
                pencil = ImageDraw.Draw(self.im)
                if abs(self.draw_flag.x() - event.pos().x()) > abs(self.draw_flag.y() - event.pos().y()):
                    pencil.line((self.draw_flag.x() - 10, self.draw_flag.y() - 10, event.pos().x() - 10,
                                 self.draw_flag.y() - 10),
                                fill=self.brushColor)
                    self.draw_flag = QPoint(event.pos().x(), self.draw_flag.y())
                else:
                    pencil.line(
                        (self.draw_flag.x() - 10, self.draw_flag.y() - 10, self.draw_flag.x() - 10,
                         event.pos().y() - 10),
                        fill=self.brushColor)
                    self.draw_flag = QPoint(self.draw_flag.x(), event.pos().y())
                self.pix = QPixmap.fromImage(ImageQt(self.im.convert("RGBA")))
                self.plat_map.setPixmap(self.pix)
                self.update()
                print(1)
            else:
                self.draw_flag = event.pos()
            self.drawing = False
            self.old_im = self.im.copy()

    def apply(self):
        pass
        # self.con = sqlite3.connect("Furniture_redactor_database.sqlite")
        # self.cur = self.con.cursor()

    def crop(self, im):
        pixels = im.load()
        x, y = im.size

        def_pix = pixels[0, 0]

        max_coorg_i = 0
        min_coorg_i = 1000000000000
        max_coorg_j = 0
        min_coorg_j = 1000000000000

        for i in range(x):
            for j in range(y):
                if pixels[i, j] != def_pix:
                    if max_coorg_i < i:
                        max_coorg_i = i
                    if min_coorg_i > i:
                        min_coorg_i = i
                    if max_coorg_j < j:
                        max_coorg_j = j
                    if min_coorg_j > j:
                        min_coorg_j = j

        return im.crop((min_coorg_i, min_coorg_j, max_coorg_i + 1, max_coorg_j + 1))
